### PR TITLE
Stop requiring this gem, I don't think we use it

### PR DESCRIPTION
**Pull request by toreriklinnerud**

### CODE REVIEW

**Comment by matteodepalo** [comment]
:+1:

**Comment by manusajith** [comment]
@toreriklinnerud I was facing load error from ci_reporter. I see that even though the PR is merged, a newer version hasn't been released to rubygems. Would be great if you can do that.

**Comment by toreriklinnerud** [comment]
@manusajith Thanks for the reminder, sorry for taking a while. A new gem version is released.

**Comment by manusajith** [comment]
:+1:

**Pull request merged**
